/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CapaVisual;

import CapaLogica.GestorLogico;
import java.awt.GraphicsEnvironment;
import javax.swing.UIManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author david.barrantes
 */
public class VVenta extends javax.swing.JFrame {
GestorLogico GL_Principal;
int Padre=0;
    /**
     * Creates new form VVenta
     */
    public VVenta(GestorLogico pGLPrincipal,int pPadre,String pcedula,String pnombre,String ptelefono,int pproc ,int renta, String pBase) {
        Padre=pPadre;
        GL_Principal=pGLPrincipal;
        try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        } catch (Exception ex) { 
            System.out.println(ex); 
        }
        
        initComponents();
        
        jComboBox2.setSelectedIndex(0);
        
        
        jLabel11.setText(GL_Principal.Usuario[0]);
        jTextField1.setText(pcedula);
        jTextField3.setText(pnombre);
        jTextField2.setText(ptelefono);
        
        jComboBox6.setSelectedIndex(pproc);
        jTextField5.setText(renta+"");
        jLabel22.setText(pBase);
        
        pack();
        
SimpleDateFormat formateador = new SimpleDateFormat(
   "hh:mm:ss' - 'dd'/'mm'/'yyyy", new Locale("es_ES"));
   Date fechaDate = new Date();
   String fecha = formateador.format(fechaDate);
   System.out.println(fecha);
        
        jLabel12.setText(fecha);
        
        jRadioButton1.setSelected(true);
        
        GraphicsEnvironment env =GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        
        llenar_lista_A();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Asesor:");

        jLabel2.setText("Producto: ");

        jLabel3.setText("Cédula:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Estado Civil");

        jLabel6.setText("Teléfono:");

        jLabel7.setText("Cantón:");

        jLabel8.setText("Provincia:");

        jLabel9.setText("Distrito:");

        jLabel14.setText("Procedencia:");

        jLabel15.setText("Producto Contratado:");

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Sin Fronteras:");

        jLabel17.setText("Renta: *");

        jLabel18.setText("Renta Anterior:");

        jLabel19.setText("Dirección:");

        jLabel23.setText("Forma de pago:");

        jLabel24.setText("Tarjeta:");

        jLabel25.setText("Anticipo:");

        jLabel26.setText("Requisitos:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casa Claro", "Data Card", "DTH", "Portabilidad", "Renovacion", "Venta Nueva" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAN JOSE", "PUNTARENAS", "LIMON", "HEREDIA", "GUANACASTE", "CARTAGO", "ALAJUELA" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "soltero(a)", "casado(a)", "divorciado(a)" }));

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Teléfono", "Parentesco"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INBOUND", "OUTBOUND" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Paga Próxima Facturacion", "Promocion", "Tarjeta" }));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("SI");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Orden Patronal");

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Cédula");

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Estados de Cuenta");

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Recibo de Servicios Públicos");

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Pasaporte");

        jLabel10.setText("Fecha:");

        jButton1.setText("Salvar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATM", "ATM:120MIN/3000SMS/5MEGAS", "ATM:180MIN/3000SMS/1MEGA", "ATM:360MIN/100SMS/1MEGA", "ATM:360MIN/500SMS/1MEGA", "ATM100MENS60MIN3MB", "ATM100MENS60MIN4MB", "ATM10100", "ATM10600FINANCIADO", "ATM120MIN100SMS512KBPS", "ATM180MIN/1000SMS/1MBPS", "ATM180MIN/1000SMS/5MBPS", "ATM180MIN500SMS1MBPS", "ATM600MIN100SMS4MBPS", "ATM600MIN3000MENS5MBINTERNET", "ATM60MIN100SMS3MBPS", "ATM60MIN500SMS2MBPS", "ATMAPORTADO", "ATMFINANCIADO", "ATMIPHONE", "ATMIPHONEPLUS16GB", "ATMM41060", "ATMS5", "ATMSAMGSUN", "ATMSONYZ3NEGRO", "ATMXPERIAE1", "BASICO", "BASICO+1", "BASICO+1+HBO", "BASICO+1+INTERNET", "BASICO+1+INTERNET+TEL", "BASICO+1+TELEFONIA", "BASICO+1+VENUS", "BASICO+1ADIC", "BASICO+1CAJA", "BASICO+1CAJA+HBO", "BASICO+1CAJA+HBO+VENUS", "BASICO+1CAJA+INTERNET", "BASICO+1STB", "BASICO+1STB+HBO", "BASICO+1STB+INTERNET", "BASICO+2", "BASICO+2+VENUS", "BASICO+2ADIC", "BASICO+2ADICIONALES", "BASICO+2CAJA", "BASICO+2CAJA+INTERNET", "BASICO+2CAJAS", "BASICO+2CAJAS+TRIPLE", "BASICO+2STB", "BASICO+3", "BASICO+3ADIC", "BASICO+3AIDC+FOX", "BASICO+3CAJA", "BASICO+3CAJAS", "BASICO+3CAJASADICIONALES", "BASICO+3STB+INTERNET+HBO", "BASICO+FOX", "BASICO+FOX+", "BASICO+FOX+HBO", "BASICO+HBO", "BASICO+HD", "BASICO+HD+INTERNET", "BASICO+INTERNET", "BASICO+INTERNET+1CAJA", "BASICO+INTERNET+2CAJAS", "BASICO+TELEFONIA+3CAJAS", "BASICOCLAROTV", "BASICOCLAROTV+1stb", "CASACALRODOBLE+1ADIC", "CASACALRODOBLE+HD", "CASACALROTV+INTERNET+TELEFONIA+2STBADICIONAL", "CASACLARO+DTH+1STB", "CASACLARO+INTERNET", "CASACLARO+INTERNET+1ADIC", "CASACLARO+INTERNET+2ADIC", "CASACLARO+INTERNET+2STB", "CASACLARO+INTERNET+CAJAADICIONAL", "CASACLARODOBLE", "CASACLARODOBLE(INTERNET)+1STB", "CASACLARODOBLE|", "CASACLARODOBLE+1CAJA", "CASACLARODOBLE+1STB", "CASACLARODOBLE+3ADIC", "CASACLARODOBLE+3STB", "CASACLARODOBLEDTH+INTERNET", "CasaClarodobletelefonia+2cajas", "CASACLAROHOGARDOBLE+2STB+INTERNET", "CASACLAROTRIPLE", "CASACLAROTRIPLE+1ADIC", "CASACLAROTRIPLE+1CAJA", "CASACLAROTRIPLE+1STB", "CASACLAROTRIPLE+2STB", "CASACLAROTRIPLE+2STB+TELEF", "CASACLAROTRIPLE+3STB+HD", "CASACLAROTRIPLEBASICO", "CASACLAROTV+INTERNET", "CASACLAROTV+INTERNET/+2CAJAS", "CASACLAROTV+INTERNET+2", "CASACLAROTV+INTERNET+2+HD", "CASACLAROTV+INTERNET+3CAJAS", "CASACLAROTV+INTERNET+TELEFONIA", "CASACLAROTV+INTERNET+TELEFONIA+1CAJA", "CASADOBLE", "CC-2", "CC3", "CC-3", "CC3GEMALTO", "CC4M44040", "CC5", "CC5SAMSUNGCORE2", "CLAROHOGARDOBLE", "CLAROHOGARDOBLE+1ADIC", "CLAROHOGARDOBLE+2STB+INTERNET", "CLAROHOGARDOBLETVEINTERNET+1CAJA", "CLAROHOGARDOBLETVEINTERNET+2CAJAS", "CLAROHOGARTRIPLE", "CLAROHOGARTRIPLE+1CAJA", "CLAROHOGARTRIPLE+2CAJA", "CLAROTRIP´LE+1CAJAADICIONAL", "CLAROTV", "CLAROTV+INTERNET", "CLAROTV+INTERNET+CAJAADICIONAL", "CLAROTV+INTERNETBASICO", "CLAROTV+TELEFONIA", "CONTROL3", "COPEEVEGA", "CUENTACONTRL", "CUENTACONTROL1", "CUENTACONTROL2", "CUENTACONTROL3", "CUENTACONTROL3APORTADO", "CUENTACONTROL3MIGRACION", "CUENTACONTROL3PORTABILIDAD", "CUENTACONTROL3PORTABILIDADSAMSUNGACE4LITEBLANCO", "CUENTACONTROL3SAMSUNGACE4LITEBLANCO", "CUENTACONTROL4", "CUENTACONTROL4SAMSUNGCORE2NEGRO", "CUENTACONTROL5", "CUENTACONTROL5MIGRACION", "CUENTACONTROLSAMSUNGACE4LITEBLANCO", "CUENTASMARTFUN3", "DATACARD", "DATACARD1MB", "DATACARD2MB", "DATACARD2MEGAS", "DATACARD4MB", "DATACARD5MB", "DATACARDPLUS", "DOBLECLARO", "DOBLECLARO+1STB", "DOBLEPLAYTELEFONIA+1STB", "DTH", "DTH+1", "DTH+1+FOX", "DTH+1STB", "DTH+1STB+INTERNET+HBO+FOX", "DTH+1STB+INTERNET+HD+VENUS", "Dth+1stb+telefonia", "DTH+1STBCASACALROTRIPLE", "DTH+2", "DTH+2+HBO+FOX", "DTH+2cajas", "DTH+2STB", "DTH+2STB+HD", "dth+3cajas", "DTH+3STB", "DTH+FOX+2STB", "DTH+FOX+HD+1STB", "DTH+HBO", "DTH+HD", "DTH+INTERNET", "DTH+STB", "DTHBASICO", "DTHBASICO+1", "DTHBASICO+1+FOX", "DTHBASICO+1+VENUS", "DTHBASICO+1STB", "DTHBASICO+2", "DTHBASICO+2+FOX", "DTHBASICO+2+TELEFONIA", "DTHBASICO+2STB", "DTHBASICO+3", "DTHBASICO+3+HBO", "DTHBASICO+3STB", "DTHDE2STB", "DTHDE2TV", "DTHDOBLE+3cajas+fox", "DTHSOLOUNTV", "FINANCIADOATMIPHONE", "GEMALTO", "GEMALTOCC3", "GEMALTOIPHONE1", "GEMALTOSUPERSTAR", "INTERNET", "INTERNET4MBPSCONMIFI", "IPHONE1", "IPHONE1SPACEGRAY16GB", "IPHONE1SPACEGRAY64GB", "IPHONE2", "IPHONE6", "IPHONE664GB", "LINEAPOSPAGOCUENTACONTROL3", "M41060", "M44045", "MI*FI5MB", "MIFI", "MI-FI", "MI-FI3MB", "MIFI3MBPS", "MIFI3MEGAS", "MIFI4MBPS", "MIFI4MEGAS", "MIFI5", "MI-FI5MB", "MIFI5MBPS", "MI-FII", "MIFII5MEGAS", "MIGRACION", "MIGRACIONAPORTADO", "MOBILNYXKYTTV", "MOBILSAMSUMGS6", "MOBILSONYZ3", "MOVIELNUEVA", "MOVIL", "MOVILATM", "MOVILCC3", "MOVILCUENTACONTROL2", "MOVILCUENTACONTROL3", "MOVILRENOVACION", "MOVILRENOVACIONM4", "MOVILRENOVACIONSVNEGRO", "MOVILSERVICIOSATM", "MOVILVENTANUEVA", "PAQUETEBASICO", "PLANFINANCIADOATM", "PLANFINANCIADOIPHONE6", "PLANIPHONE1", "PLANSMARTFUN3", "PORTABILIDAD", "PORTABILIDADCC3", "PORTABILIDADCC5", "portabilidadconmovil", "PORTABILIDADCONPLAN", "PORTABILIDADPOSPAGOATM", "PORTAVILIDADATM", "PORTAVILIDADCC3", "RENOVACION", "RENOVACIONATM", "RENOVACIONCC3", "RENOVACIONCC5", "RENOVACIONDATACARD", "RENOVACIONIPHONE", "RENOVACIONIPHONE1", "RENOVACIONLGG3", "RENOVACIONM44040", "RENOVACIONM44045", "RENOVACIONMI-FI", "RENOVACIONPLAN", "RENOVACIONPLANIPHONE1", "RENOVACIONSAMSUNGCORE2NEGRO", "RENOVACIONSAMSUNGGALAXIS6", "RENOVMISMO", "RONOVACIONM44045", "SMARTFUN3", "SUPERSTAR", "SUPERSTARACE4", "SUPERSTARM44045", "SUPERSTARM44045BLANCO", "TRIPLE", "TRIPLECASACLARO", "TURBONET", "TURBONETFULL", "TV", "TV+INTERNET+1CAJA", "VENTAMOVIL", "VENTAMOVILNUEVA", "VENTANUEVA" }));

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("Monto: ");

        jLabel20.setText("Referencias: *");

        jLabel21.setText("* Obligatorio");

        jLabel22.setText("Base");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel10))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox3, 0, 171, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(46, 46, 46)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addGap(107, 107, 107)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4))
                            .addComponent(jTextField7)
                            .addComponent(jTextField6)
                            .addComponent(jTextField5)
                            .addComponent(jCheckBox1)
                            .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel13)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel21)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Nombre", "Telefono", "Status"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel27.setText("Búsqueda por cédula:");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar Filtro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
jRadioButton1.setSelected(true);
jRadioButton2.setSelected(false);

// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GL_Principal.Regresar_Venta(Padre);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
     jRadioButton1.setSelected(false);
     jRadioButton2.setSelected(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String 
        Asesor=jLabel11.getText(), 
        Producto=jComboBox1.getSelectedItem().toString(), 
        Cedula_Cliente=jTextField1.getText(), 
        Nombre_Cliente=jTextField3.getText(), 
        Estado_Civil=jComboBox3.getSelectedItem().toString(), 
        Telefono_Cliente=jTextField2.getText(), 
        Provincia=jComboBox2.getSelectedItem().toString(), 
        Canton=jComboBox4.getSelectedItem().toString(), 
        Distrito=jComboBox5.getSelectedItem().toString(), 
        Direccion=jTextArea1.getText(), 
        Procedencia=jComboBox6.getSelectedItem().toString(),
        Producto_Contratado=jComboBox9.getSelectedItem().toString(),
        Tipo_Renta=jComboBox7.getSelectedItem().toString(),
        Mnto_Renta=jTextField5.getText(), 
        Renta_Anterior=jTextField6.getText(), 
        Forma_Pago=jComboBox8.getSelectedItem().toString(),
        Tarjeta=jTextField7.getText(), 
        Anticipo_opcion, 
        Anticipo_Monto=jTextField4.getText(), 
        R_Orden, 
        R_Ced, 
        R_EstadosCta, 
        R_Recibo, 
        R_Pasaporte, 
        Referencia1_Nombre="NA",
        Referencia1_Telefono="NA",
        Referencia1_Parentesco="NA",
        Referencia2_Nombre="NA",
        Referencia2_Telefono="NA",
        Referencia2_Parentesco="NA",
        Base=jLabel22.getText(); 
        
        try{Referencia1_Nombre=jTable1.getValueAt(0, 0).toString();}catch(Exception ex){}
        try{Referencia1_Telefono=jTable1.getValueAt(0, 1).toString();}catch(Exception ex){}
        try{Referencia1_Parentesco=jTable1.getValueAt(0, 2).toString();}catch(Exception ex){}
        try{Referencia2_Nombre=jTable1.getValueAt(1, 0).toString();}catch(Exception ex){}
        try{Referencia2_Telefono=jTable1.getValueAt(1, 1).toString();}catch(Exception ex){}
        try{Referencia2_Parentesco=jTable1.getValueAt(1, 2).toString();}catch(Exception ex){}
        
        
        
if(jRadioButton1.isSelected()){
    Anticipo_opcion="SI";
}else{
    Anticipo_opcion="NO";
}

if(jCheckBox1.isSelected()){
    R_Orden="SI";
}else{
    R_Orden="NO";
}

if(jCheckBox2.isSelected()){
    R_Ced="SI";
}else{
    R_Ced="NO";
}

if(jCheckBox3.isSelected()){
    R_EstadosCta="SI";
}else{
    R_EstadosCta="NO";
}

if(jCheckBox4.isSelected()){
    R_Recibo="SI";
}else{
    R_Recibo="NO";
}

if(jCheckBox5.isSelected()){
    R_Pasaporte="SI";
}else{
    R_Pasaporte="NO";
}




try{
    GL_Principal.Insertar_Venta(Asesor, Producto, Cedula_Cliente, Nombre_Cliente, Estado_Civil, Telefono_Cliente, Provincia, Canton, Distrito, Direccion, Procedencia, Producto_Contratado, Tipo_Renta, Integer.parseInt(Mnto_Renta), Renta_Anterior, Forma_Pago, Tarjeta, Anticipo_opcion, Anticipo_Monto, R_Orden, R_Ced, R_EstadosCta, R_Recibo, R_Pasaporte, Referencia1_Nombre, Referencia1_Telefono, Referencia1_Parentesco, Referencia2_Nombre, Referencia2_Telefono, Referencia2_Parentesco,Base);
    llenar_lista_A();
}catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex, "VENTANA VENTA", JOptionPane.WARNING_MESSAGE);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
//provincia selected
jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(devolver_cantones(jComboBox2.getSelectedItem().toString())));
              
jComboBox4.setSelectedIndex(0);        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed

jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(devolver_distritos(jComboBox4.getSelectedItem().toString())));        
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

llenar_lista_B();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

llenar_lista_A();        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private String[] devolver_cantones(String pProvincia){
        
        
String[] array1=new String[]{
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"GUANACASTE",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE",
"SAN JOSE"};

String[] array2=new String[]{
"ALAJUELA",
"ALFARO RUIZ",
"ATENAS",
"EL ERIZO(MRL)",
"EL INFIERNILLO(MRL)",
"GRECIA",
"GUATUSO",
"INVU LAS CAÑAS #1(MRL)",
"LOS CHILES",
"NARANJO",
"OROTINA",
"PALMARES",
"POAS",
"SAN CARLOS",
"SAN MATEO",
"SAN RAMON",
"TROPICO 1 Y 2(MRL)",
"TUETAL SUR(MRL)",
"UPALA",
"VALVERDE VEGA",
"ALVARADO",
"CALLE CHOCOLATE(MRL)",
"CARTAGO",
"COCORÍ DEBAJO DE LOURDES(MRL)",
"EL DIQUE DE SAN NICOLAS(MRL)",
"EL GUARCO",
"JIMENEZ",
"LA UNION",
"OREAMUNO",
"PARAISO",
"TURRIALBA",
"URBANIZACION SANTA LUCIA (LAS LTAS DE PARAISO)(MRL)",
"ABANGARES",
"BAGACES",
"BARRIO SAN MARTIN DE NICOYA (LAS LATAS)(MRL)",
"CAÑAS",
"CARRILLO",
"HOJANCHA",
"LA CRUZ",
"LIBERIA",
"NANDAYURE",
"NICOYA",
"SANTA CRUZ",
"TILARAN",
"BARVA",
"BELEN",
"FLORES",
"HEREDIA",
"LA CUENCA DE GUARARÍA(MRL)",
"LA LUCÍA(MRL)",
"LOS RANCHOS DETRÁS DEL MALL PASEO DE LAS FLORES(MRL)",
"SAN ISIDRO",
"SAN PABLO",
"SAN RAFAEL",
"SANTA BARBARA",
"SANTO DOMINGO",
"SARAPIQUI",
"CIENEGUITA(MRL)",
"EMBACO(MRL)",
"GUACIMO",
"LIMON",
"LIMON 2000(MRL)",
"LIRIO(MRL)",
"MATINA",
"POCOCI",
"SIQUIRRES",
"TALAMANCA",
"TICABAN(MRL)",
"AGUIRRE",
"BUENOS AIRES",
"CERCA DE LA ZONA FRANCA DEL ROBLE(MRL)",
"CORREDORES",
"COTO BRUS",
"ESPARZA",
"FRAICASIANO(MRL)",
"GARABITO",
"GOLFITO",
"MONTES DE ORO",
"OSA",
"PARRITA",
"PUNTARENAS",
"ZAPOCHINGO DE BARRANCA(MRL)",
"ACOSTA",
"ALAJUELITA",
"ASERRI",
"CENTRAL",
"CORONADO",
"CURRIDABAT",
"DESAMPARADOS",
"DOTA",
"ESCAZU",
"GOICOECHEA",
"LEON CORTES",
"MONTES DE OCA",
"MORA",
"MORAVIA",
"PEREZ ZELEDON",
"PURISCAL",
"SANTA ANA",
"TARRAZU",
"TIBAS",
"TURRUBARES",
"15 SETIEMBRE(MRL)",
"AGUANTA FILO (ENTRE HATILLO Y SAN SEBAS)(MRL)",
"CARBONERA PASO ANCHO(MRL)",
"CASA MUÑECAS HATILLO 8(MRL)",
"CRISTO REY(MRL)",
"DETRÁS DE MULTIPLAZA DEL ESTE (MRL)",
"FINCA SAN JUAN DE PAVAS(MRL)",
"LA CARPIO EN LA CUEVA DEL SAPO(MRL)",
"LAS TABLAS DE DESAMPARADOS(MRL)",
"LEON XIII(MRL)",
"LINDA VISTA *ALGUNOS SECTORES(MRL)",
"LOS FILTROS DE ALAJUELITA(MRL)",
"LOS GUIDOS SECTOR 8 Y LO QUE UNO LOS GUIDO CON PATARRA(MRL)",
"POCHOTE BARRIO CUBA(MRL)",
"PURRAL EL ALTO (LA CHANITA HACIA EL ESTE EL MATADERO SECTORES 2 3 4 CALLE COLOCHOS CALLE EL 84 EL EDEN(MRL)",
"ROSISTEER CARBALLO URUCA(MRL)",
"SAGRADA FAMILIA(MRL)",
"TEJARCILLOS DE ALAJUELITA(MRL)",
"TIRRASES DE LA ULTIMA PARDA EN ADELANTE(MRL)",
"TORREMOLINOS DESAMPARADOS(MRL)",
"TRIANGULO DE LA SOLIDARIDAD(MRL)",
"VILLA ESPERANZA DE PAVAS(MRL)"
};

int elementos=0;
        for (int i = 0; i < array1.length; i++) {
            if(array1[i].equals(pProvincia)){
                elementos++;
            }
        }      

String[] resultado = new String[elementos];

int x=0;
for (int i = 0; i < array1.length; i++) {
            if(array1[i].equals(pProvincia)){
               resultado[x]=array2[i];
               x++;
            }
        } 
        
      
        return resultado;
    }
    private String[] devolver_distritos(String pCanton){
        
String[] array1,array2;

array1 = new String[]{
"15 SETIEMBRE(MRL)",
"ABANGARES",
"ABANGARES",
"ABANGARES",
"ABANGARES",
"ACOSTA",
"ACOSTA",
"ACOSTA",
"ACOSTA",
"ACOSTA",
"AGUANTA FILO (ENTRE HATILLO Y SAN SEBAS)(MRL)",
"AGUIRRE",
"AGUIRRE",
"AGUIRRE",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELA",
"ALAJUELITA",
"ALAJUELITA",
"ALAJUELITA",
"ALAJUELITA",
"ALAJUELITA",
"ALFARO RUIZ",
"ALFARO RUIZ",
"ALFARO RUIZ",
"ALFARO RUIZ",
"ALFARO RUIZ",
"ALFARO RUIZ",
"ALFARO RUIZ",
"ALVARADO",
"ALVARADO",
"ALVARADO",
"ASERRI",
"ASERRI",
"ASERRI",
"ASERRI",
"ASERRI",
"ASERRI",
"ASERRI",
"ATENAS",
"ATENAS",
"ATENAS",
"ATENAS",
"ATENAS",
"ATENAS",
"ATENAS",
"BAGACES",
"BAGACES",
"BAGACES",
"BAGACES",
"BARRIO SAN MARTIN DE NICOYA (LAS LATAS)(MRL)",
"BARVA",
"BARVA",
"BARVA",
"BARVA",
"BARVA",
"BARVA",
"BELEN",
"BELEN",
"BELEN",
"BUENOS AIRES",
"BUENOS AIRES",
"BUENOS AIRES",
"BUENOS AIRES",
"BUENOS AIRES",
"BUENOS AIRES",
"BUENOS AIRES",
"BUENOS AIRES",
"BUENOS AIRES",
"CALLE CHOCOLATE(MRL)",
"CAÑAS",
"CAÑAS",
"CAÑAS",
"CAÑAS",
"CAÑAS",
"CARBONERA PASO ANCHO(MRL)",
"CARRILLO",
"CARRILLO",
"CARRILLO",
"CARRILLO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CARTAGO",
"CASA MUÑECAS HATILLO 8(MRL)",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CENTRAL",
"CERCA DE LA ZONA FRANCA DEL ROBLE(MRL)",
"CIENEGUITA(MRL)",
"COCORÍ DEBAJO DE LOURDES(MRL)",
"CORONADO",
"CORONADO",
"CORONADO",
"CORONADO",
"CORONADO",
"CORREDORES",
"CORREDORES",
"CORREDORES",
"CORREDORES",
"COTO BRUS",
"COTO BRUS",
"COTO BRUS",
"COTO BRUS",
"COTO BRUS",
"CRISTO REY(MRL)",
"CURRIDABAT",
"CURRIDABAT",
"CURRIDABAT",
"CURRIDABAT",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DESAMPARADOS",
"DETRÁS DE MULTIPLAZA DEL ESTE (MRL)",
"DOTA",
"DOTA",
"DOTA",
"EL DIQUE DE SAN NICOLAS(MRL)",
"EL ERIZO(MRL)",
"EL GUARCO",
"EL GUARCO",
"EL GUARCO",
"EL GUARCO",
"EL INFIERNILLO(MRL)",
"EMBACO(MRL)",
"ESCAZU",
"ESCAZU",
"ESCAZU",
"ESPARZA",
"ESPARZA",
"ESPARZA",
"ESPARZA",
"ESPARZA",
"FINCA SAN JUAN DE PAVAS(MRL)",
"FLORES",
"FLORES",
"FLORES",
"FRAICASIANO(MRL)",
"GARABITO",
"GARABITO",
"GOICOECHEA",
"GOICOECHEA",
"GOICOECHEA",
"GOICOECHEA",
"GOICOECHEA",
"GOICOECHEA",
"GOICOECHEA",
"GOLFITO",
"GOLFITO",
"GOLFITO",
"GOLFITO",
"GRECIA",
"GRECIA",
"GRECIA",
"GRECIA",
"GRECIA",
"GRECIA",
"GRECIA",
"GRECIA",
"GUACIMO",
"GUACIMO",
"GUACIMO",
"GUACIMO",
"GUACIMO",
"GUATUSO",
"GUATUSO",
"GUATUSO",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HEREDIA",
"HOJANCHA",
"HOJANCHA",
"HOJANCHA",
"HOJANCHA",
"INVU LAS CAÑAS #1(MRL)",
"JIMENEZ",
"JIMENEZ",
"JIMENEZ",
"LA CARPIO EN LA CUEVA DEL SAPO(MRL)",
"LA CRUZ",
"LA CRUZ",
"LA CRUZ",
"LA CRUZ",
"LA CUENCA DE GUARARÍA(MRL)",
"LA LUCÍA(MRL)",
"LA UNION",
"LA UNION",
"LA UNION",
"LA UNION",
"LA UNION",
"LA UNION",
"LA UNION",
"LA UNION",
"LAS TABLAS DE DESAMPARADOS(MRL)",
"LEON CORTES",
"LEON CORTES",
"LEON CORTES",
"LEON CORTES",
"LEON CORTES",
"LEON CORTES",
"LEON XIII(MRL)",
"LIBERIA",
"LIBERIA",
"LIBERIA",
"LIBERIA",
"LIBERIA",
"LIMON",
"LIMON",
"LIMON",
"LIMON",
"LIMON 2000(MRL)",
"LINDA VISTA *ALGUNOS SECTORES(MRL)",
"LIRIO(MRL)",
"LOS CHILES",
"LOS CHILES",
"LOS CHILES",
"LOS CHILES",
"LOS FILTROS DE ALAJUELITA(MRL)",
"LOS GUIDOS SECTOR 8 Y LO QUE UNO LOS GUIDO CON PATARRA(MRL)",
"LOS RANCHOS DETRÁS DEL MALL PASEO DE LAS FLORES(MRL)",
"MATINA",
"MATINA",
"MATINA",
"MONTES DE OCA",
"MONTES DE OCA",
"MONTES DE OCA",
"MONTES DE OCA",
"MONTES DE ORO",
"MONTES DE ORO",
"MONTES DE ORO",
"MORA",
"MORA",
"MORA",
"MORA",
"MORA",
"MORAVIA",
"MORAVIA",
"MORAVIA",
"NANDAYURE",
"NANDAYURE",
"NANDAYURE",
"NANDAYURE",
"NANDAYURE",
"NANDAYURE",
"NARANJO",
"NARANJO",
"NARANJO",
"NARANJO",
"NARANJO",
"NARANJO",
"NARANJO",
"NICOYA",
"NICOYA",
"NICOYA",
"NICOYA",
"NICOYA",
"NICOYA",
"NICOYA",
"OREAMUNO",
"OREAMUNO",
"OREAMUNO",
"OREAMUNO",
"OREAMUNO",
"OROTINA",
"OROTINA",
"OROTINA",
"OROTINA",
"OROTINA",
"OSA",
"OSA",
"OSA",
"OSA",
"OSA",
"PALMARES",
"PALMARES",
"PALMARES",
"PALMARES",
"PALMARES",
"PALMARES",
"PALMARES",
"PARAISO",
"PARAISO",
"PARAISO",
"PARAISO",
"PARRITA",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"PEREZ ZELEDON",
"POAS",
"POAS",
"POAS",
"POAS",
"POAS",
"POCHOTE BARRIO CUBA(MRL)",
"POCOCI",
"POCOCI",
"POCOCI",
"POCOCI",
"POCOCI",
"POCOCI",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PUNTARENAS",
"PURISCAL",
"PURISCAL",
"PURISCAL",
"PURISCAL",
"PURISCAL",
"PURISCAL",
"PURISCAL",
"PURISCAL",
"PURISCAL",
"PURRAL EL ALTO (LA CHANITA HACIA EL ESTE EL MATADERO SECTORES 2 3 4 CALLE COLOCHOS CALLE EL 84 EL EDEN(MRL)",
"ROSISTEER CARBALLO URUCA(MRL)",
"SAGRADA FAMILIA(MRL)",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN CARLOS",
"SAN ISIDRO",
"SAN ISIDRO",
"SAN ISIDRO",
"SAN ISIDRO",
"SAN MATEO",
"SAN MATEO",
"SAN MATEO",
"SAN PABLO",
"SAN RAFAEL",
"SAN RAFAEL",
"SAN RAFAEL",
"SAN RAFAEL",
"SAN RAFAEL",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SAN RAMON",
"SANTA ANA",
"SANTA ANA",
"SANTA ANA",
"SANTA ANA",
"SANTA ANA",
"SANTA ANA",
"SANTA BARBARA",
"SANTA BARBARA",
"SANTA BARBARA",
"SANTA BARBARA",
"SANTA BARBARA",
"SANTA BARBARA",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTA CRUZ",
"SANTO DOMINGO",
"SANTO DOMINGO",
"SANTO DOMINGO",
"SANTO DOMINGO",
"SANTO DOMINGO",
"SANTO DOMINGO",
"SANTO DOMINGO",
"SANTO DOMINGO",
"SARAPIQUI",
"SARAPIQUI",
"SARAPIQUI",
"SARAPIQUI",
"SARAPIQUI",
"SIQUIRRES",
"SIQUIRRES",
"SIQUIRRES",
"SIQUIRRES",
"SIQUIRRES",
"SIQUIRRES",
"TALAMANCA",
"TALAMANCA",
"TALAMANCA",
"TARRAZU",
"TARRAZU",
"TARRAZU",
"TEJARCILLOS DE ALAJUELITA(MRL)",
"TIBAS",
"TIBAS",
"TIBAS",
"TIBAS",
"TIBAS",
"TICABAN(MRL)",
"TILARAN",
"TILARAN",
"TILARAN",
"TILARAN",
"TILARAN",
"TILARAN",
"TILARAN",
"TIRRASES DE LA ULTIMA PARDA EN ADELANTE(MRL)",
"TORREMOLINOS DESAMPARADOS(MRL)",
"TRIANGULO DE LA SOLIDARIDAD(MRL)",
"TROPICO 1 Y 2(MRL)",
"TUETAL SUR(MRL)",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRIALBA",
"TURRUBARES",
"TURRUBARES",
"TURRUBARES",
"TURRUBARES",
"UPALA",
"UPALA",
"UPALA",
"UPALA",
"UPALA",
"UPALA",
"UPALA",
"URBANIZACION SANTA LUCIA (LAS LTAS DE PARAISO)(MRL)",
"VALVERDE VEGA",
"VALVERDE VEGA",
"VALVERDE VEGA",
"VALVERDE VEGA",
"VALVERDE VEGA",
"VILLA ESPERANZA DE PAVAS(MRL)",
"ZAPOCHINGO DE BARRANCA(MRL)"
};
array2 = new String[]{
"N/A",
"LAS JUNTAS",
"SIERRA",
"SAN JUAN",
"COLORADO",
"SAN IGNACIO",
"GUAITIL",
"PALMICHAL",
"CANGREJAL",
"SABANILLAS",
"N/A",
"QUEPOS",
"SAVEGRE",
"NARANJITO",
"ALAJUELA",
"SAN JOSE",
"CARRIZAL",
"SAN ANTONIO",
"GUACIMA",
"SAN ISIDRO",
"SABANILLA",
"SAN RAFAEL",
"RIO SEGUNDO",
"DESAMPARADOS",
"TURRUCARES",
"TAMBOR",
"LA GARITA",
"SAN MIGUEL DE SARAPIQUI",
"ALAJUELITA",
"SAN JOSECITO",
"SAN ANTONIO",
"CONCEPCION",
"SAN FELIPE",
"ZARCERO",
"LAGUNA",
"TAPEZCO",
"GUADALUPE",
"PALMIRA",
"ZAPOTE",
"BRISAS",
"PACAYAS",
"CERVANTES",
"CAPELLADES",
"ASERRI",
"TARBACA",
"VUELTA DE JORCO",
"SAN GABRIEL",
"LA LEGUA",
"MONTERREY",
"SALITRILLOS",
"ATENAS",
"JESUS",
"MERCEDES",
"SAN ISIDRO",
"CONCEPCION",
"SAN JOSE",
"SANTA EULALIA",
"BAGACES",
"FORTUNA",
"MOGOTE",
"RIO NARANJO",
"N/A",
"BARVA",
"SAN PEDRO",
"SAN PABLO",
"SAN ROQUE",
"SANTA LUCIA",
"SAN JOSE DE LA MONTAÑA",
"SAN ANTONIO",
"LA RIBERA",
"ASUNCION",
"BUENOS AIRES",
"VOLCAN",
"POTRERO GRANDE",
"BORUCA",
"PILAS",
"COLINAS",
"CHANGUENA",
"BIOLLEY",
"BRUNKA",
"N/A",
"CAÑAS",
"PALMIRA",
"SAN MIGUEL",
"BEBEDERO",
"POROSAL",
"N/A",
"FILADELFIA",
"PALMIRA",
"SARDINAL",
"BELEN",
"PARTE ORIENTAL ",
"PARTE OCCIDENTAL",
"CARMEN",
"SAN NICOLAS",
"SAN FRANCISCO",
"GUADALUPE",
"CORRALILLO",
"TIERRA BLANCA",
"DULCE NOMBRE",
"LLANO GRANDE",
"QUEBRADILLAS",
"N/A",
"CARMEN (NE)",
"MERCED (NO)",
"Division ",
"CATEDRAL (SE)",
"ZAPOTE",
"SAN FCO. 2 RIOS",
"URUCA",
"MATA REDONDA",
"PAVAS",
"HATILLO",
"SAN SEBASTIAN",
"N/A",
"N/A",
"N/A",
"SAN ISIDRO",
"SAN RAFAEL",
"DULCE NOMBRE DE JESUS",
"PATALILLO",
"CASCAJAL",
"CORREDOR",
"LA CUESTA",
"CANOAS",
"LAUREL",
"SAN VITO",
"SABALITO",
"AGUA BUENA",
"LIMONCITO",
"PITTIER",
"N/A",
"CURRIDABAT",
"GRANADILLA",
"SANCHEZ",
"TIRRASES",
"DESAMPARADOS",
"SAN MIGUEL",
"SAN JUAN DE DIOS",
"SAN RAFAEL ARRIBA",
"SAN ANTONIO",
"FRAILES",
"PATARRA",
"SAN CRISTOBAL",
"ROSARIO",
"DAMAS",
"SAN RAFAEL ABAJO",
"GRAVILIAS",
"N/A",
"SANTA MARIA",
"JARDIN",
"COPEY",
"N/A",
"N/A",
"EL TEJAR",
"SAN ISIDRO",
"TOBOSI",
"PATIO DE AGUA",
"N/A",
"N/A",
"ESCAZU",
"SAN ANTONIO",
"SAN RAFAEL",
"ESPIRITU SANTO",
"SAN JUAN GRANDE",
"MACACONA",
"SAN RAFAEL",
"SAN JERONIMO",
"N/A",
"SAN JOAQUIN",
"BARRANTES",
"LLORENTE",
"N/A",
"JACO",
"TARCOLES",
"GUADALUPE",
"SAN FRANCISCO",
"CALLE BLANCOS",
"MATA DE PLATANO",
"IPIS",
"RANCHO REDONDO",
"PURRAL",
"GOLFITO",
"JIMENEZ",
"GUAYCARA",
"PAVON / PAVONES",
"GRECIA",
"SAN ISIDRO",
"SAN JOSE",
"SAN ROQUE",
"TACARES",
"RIO CUARTO",
"PUENTE DE PIEDRA",
"BOLIVAR",
"GUACIMO",
"MERCEDES",
"POCORA",
"RIO JIMENEZ",
"DUACARI",
"SAN RAFAEL",
"BUENAVISTA",
"COTE",
"HEREDIA",
"MERCEDES",
"SAN FRANCISCO",
"ULLOA",
"VARABLANCA",
"HOJANCHA",
"MONTE ROMO",
"PUERTO CARRILLO",
"HUACAS",
"N/A",
"JUAN VIÑAS",
"TUCURRIQUE",
"PEJIBAYE",
"N/A",
"LA CRUZ",
"SANTA CECILIA",
"LA GARITA",
"SANTA ELENA",
"N/A",
"N/A",
"TRES RIOS 3 RIOS",
"SAN DIEGO",
"SAN JUAN",
"SAN RAFAEL",
"CONCEPCION",
"DULCE NOMBRE",
"SAN RAMON",
"RIO AZUL",
"N/A",
"SAN PABLO",
"SAN ANDRES",
"LLANO BONITO",
"SAN ISIDRO",
"SANTA CRUZ",
"SAN ANTONIO",
"N/A",
"LIBERIA",
"CAÑAS DULCES",
"MAYORGA",
"NACASCOLO",
"CURUBANDE",
"LIMON",
"VALLE LA ESTRELLA",
"LIVERPOOL",
"MATAMA",
"N/A",
"N/A",
"N/A",
"LOS CHILES",
"CAÑO NEGRO",
"EL AMPARO",
"SAN JORGE",
"N/A",
"N/A",
"N/A",
"MATINA",
"BATAN",
"CARRANDI",
"SAN PEDRO",
"SABANILLA",
"MERCEDES",
"SAN RAFAEL",
"MIRAMAR",
"UNION",
"SAN ISIDRO",
"COLON",
"GUAYABO",
"TABARCIA",
"PIEDRAS NEGRAS",
"PICAGRES",
"SAN VICENTE",
"SAN JERONIMO",
"TRINIDAD",
"CARMONA",
"SANTA RITA",
"ZAPOTAL",
"SAN PABLO",
"PORVENIR",
"BEJUCO",
"NARANJO",
"SAN MIGUEL",
"SAN JOSE",
"CIRRI SUR",
"SAN JERONIMO",
"SAN JUAN",
"ROSARIO",
"NICOYA",
"MANSION",
"SAN ANTONIO",
"QUEBRADA HONDA",
"SAMARA",
"NOSARA",
"BELEN DE NOSARITA",
"SAN RAFAEL",
"COT",
"POTRERO CERRADO",
"CIPRESES",
"SANTA ROSA",
"OROTINA",
"MASTATE",
"HACIENDA VIEJA",
"COYOLAR",
"CEIBA",
"CORTES",
"PALMAR",
"SIERPE",
"BAHIA BALLENA",
"PIEDRAS BLANCAS",
"PALMARES",
"ZARAGOZA",
"BUENOS AIRES",
"SANTIAGO",
"CANDELARIA",
"ESQUIPULAS",
"GRANJA",
"PARAISO",
"SANTIAGO",
"OROSI",
"CACHI",
"PARRITA",
"SAN ISIDRO",
"GENERAL",
"DANIEL FLORES",
"RIVAS",
"SAN PEDRO",
"PLATANARES",
"PEJIBAYE",
"CAJON",
"BARU",
"RIO NUEVO",
"PARAMO",
"SAN PEDRO",
"SAN JUAN",
"SAN RAFAEL",
"CARRILLOS",
"SABANA REDONDA",
"N/A",
"GUAPILES",
"JIMENEZ",
"RITA",
"ROXANA",
"CARIARI",
"COLORADO",
"PUNTARENAS",
"PITAHAYA",
"CHOMES",
"LEPANTO",
"PAQUERA",
"MANZANILLO",
"GUACIMAL",
"BARRANCA",
"MONTE VERDE",
"ISLA DEL CORO",
"COBANO",
"CHACARITA",
"CHIRA",
"ACAPULCO",
"EL ROBLE",
"ARANCIBIA",
"SANTIAGO",
"MERCEDES SUR",
"BARBACOAS",
"GRIFO ALTO",
"SAN RAFAEL",
"CANDELARITA",
"DESAMPARADITOS",
"SAN ANTONIO",
"CHIRES",
"N/A",
"N/A",
"N/A",
"QUESADA",
"FLORENCIA",
"BUENAVISTA",
"AGUAS ZARCAS",
"VENECIA",
"PITAL",
"FORTUNA",
"TIGRA",
"PALMERA",
"VENADO",
"CUTRIS",
"MONTERREY",
"POCOSOL",
"SAN ISIDRO",
"SAN JOSE",
"CONCEPCION",
"SAN FRANCISCO",
"SAN MATEO",
"DESMONTE",
"JESUS MARIA",
"SAN PABLO",
"SAN RAFAEL",
"SAN JOSECITO",
"SANTIAGO",
"LOS ANGELES",
"CONCEPCION",
"SAN RAMON",
"SANTIAGO",
"SAN JUAN",
"PIEDADES NORTE",
"PIEDADES SUR",
"SAN RAFAEL",
"SAN ISIDRO",
"ANGELES",
"ALFARO",
"VOLIO",
"CONCEPCION",
"ZAPOTAL",
"PEÑAS BLANCAS",
"SANTA ANA",
"SALITRAL",
"POZOS",
"URUCA",
"PIEDADES",
"BRASIL",
"SANTA BARBARA",
"SAN PEDRO",
"SAN JUAN",
"JESUS",
"SANTO DOMINGO",
"PURABA",
"SANTA CRUZ",
"BOLSON",
"VEINTISIETE DE ABRIL 27 D",
"TEMPATE",
"CARTAGENA",
"CUAJINIQUIL",
"DIRIA",
"CABO VELAS",
"TAMARINDO",
"SANTO DOMINGO",
"SAN VICENTE",
"SAN MIGUEL",
"PARACITO",
"SANTO TOMAS",
"SANTO ROSA",
"TURES",
"PARA",
"PUERTO VIEJO",
"LA VIRGEN",
"HORQUETAS",
"LLANURAS DEL GASPAR",
"CUREÑA",
"SIQUIRRES",
"PACUARITO",
"FLORIDA",
"GERMANIA",
"CAIRO",
"ALEGRIA",
"BRATSI",
"SIXAOLA",
"CAHUITA",
"SAN MARCOS",
"SAN LORENZO",
"SAN CARLOS",
"N/A",
"SAN JUAN",
"CINCO ESQUINAS",
"ANSELMO LLORENTE",
"LEON XIII",
"COLIMA",
"N/A",
"TILARAN",
"QUEBRADA GRANDE",
"TRONADORA",
"SANTA ROSA",
"LIBANO",
"TIERRAS MORENAS",
"ARENAL",
"N/A",
"N/A",
"N/A",
"N/A",
"N/A",
"TURRIALBA",
"LA SUIZA",
"PERALTA",
"SANTA CRUZ",
"SANTA TERESITA",
"PAVONES",
"TUIS",
"TAYUTIC",
"SANTA ROSA",
"TRES EQUIS",
"LA ISABEL",
"EL CHIRRIPO",
"SAN PABLO",
"SAN PEDRO",
"SAN JUAN DE MATA // CARARA",
"SAN LUIS",
"UPALA",
"AGUAS CLARAS",
"SAN JOSE ( PIZOTE)",
"BIJAGUA",
"DELICIAS",
"DOS RIOS",
"YOLILLAL",
"N/A",
"SARCHI NORTE",
"SARCHI SUR",
"TORO AMARILLO",
"SAN PEDRO",
"RODRIGUEZ",
"N/A",
"N/A"
};        

int elementos=0;
        for (int i = 0; i < array1.length; i++) {
            if(array1[i].equals(pCanton)){
                elementos++;
            }
        }      

String[] resultado = new String[elementos];

int x=0;
for (int i = 0; i < array1.length; i++) {
            if(array1[i].equals(pCanton)){
               resultado[x]=array2[i];
               x++;
            }
        } 
        
      
        return resultado;
    }
    
    private void llenar_lista_A(){
        try{
            String[] encabezadoA={"Cod","Fecha Venta","Cliente","Teléfono","Status"};

            jTable2.setModel(new javax.swing.table.DefaultTableModel(GL_Principal.Traer_Venta(GL_Principal.Usuario[0]),encabezadoA));
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(70);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex, "VENTANA OUT_BOUND", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }
    
    private void llenar_lista_B(){
        try{
            String[] encabezadoA={"Cod","Fecha Venta","Cliente","Teléfono","Status"};

            jTable2.setModel(new javax.swing.table.DefaultTableModel(GL_Principal.Traer_Venta_B(jTextField8.getText()),encabezadoA));
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(70);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex, "VENTANA OUT_BOUND", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
